# GitHub Sponsors configuration (optional)
# Uncomment and add your sponsor information if desired

# github: [lewisflude]
# patreon: yourusername
# ko_fi: yourusername
# custom: ["https://paypal.me/yourusername", "https://buymeacoffee.com/yourusername"]
