{
  config,
  lib,
  signalColors,
  signalLib,
  ...
}:
# CONFIGURATION METHOD: raw-config (Tier 4)
# HOME-MANAGER MODULE: programs.emacs.extraConfig
# UPSTREAM SCHEMA: https://www.gnu.org/software/emacs/manual/html_node/emacs/Custom-Themes.html
# SCHEMA VERSION: 29.1
# LAST VALIDATED: 2026-01-17
# NOTES: Emacs requires Elisp for theme definition. Home-Manager provides extraConfig
#        for custom Elisp. We generate a custom theme using deftheme and custom-theme-set-faces.
let
  inherit (lib) mkIf;
  cfg = config.theming.signal;

  colors = {
    # Base colors
    bg = signalColors.tonal."surface-Lc05".hex;
    bg-alt = signalColors.tonal."surface-Lc10".hex;
    bg-highlight = signalColors.tonal."surface-Lc15".hex;
    fg = signalColors.tonal."text-Lc75".hex;
    fg-alt = signalColors.tonal."text-Lc60".hex;
    fg-dim = signalColors.tonal."text-Lc45".hex;
    border = signalColors.tonal."divider-Lc15".hex;

    # Accent colors
    blue = signalColors.accent.focus.Lc75.hex;
    cyan = signalColors.accent.info.Lc75.hex;
    green = signalColors.accent.success.Lc75.hex;
    red = signalColors.accent.danger.Lc75.hex;
    orange = signalColors.accent.warning.Lc75.hex;
    purple = signalColors.accent.special.Lc75.hex;

    # Categorical
    yellow = signalColors.categorical.GA04.hex;
    teal = signalColors.categorical.GA02.hex;
  };

  # Check if emacs should be themed
  shouldTheme = signalLib.shouldThemeApp "emacs" [
    "editors"
    "emacs"
  ] cfg config;
in
{
  config = mkIf (cfg.enable && shouldTheme) {
    programs.emacs.extraConfig = ''
      ;;; Signal Emacs Theme
      ;;; Generated by signal-nix

      (deftheme signal
        "Signal Design System theme for Emacs")

      (let ((class '((class color) (min-colors 89))))
        (custom-theme-set-faces
         'signal

         ;; Base faces
         `(default ((,class (:foreground "${colors.fg}" :background "${colors.bg}"))))
         `(cursor ((,class (:background "${colors.blue}"))))
         `(region ((,class (:background "${colors.bg-highlight}"))))
         `(highlight ((,class (:background "${colors.bg-alt}"))))
         `(hl-line ((,class (:background "${colors.bg-alt}"))))
         `(fringe ((,class (:background "${colors.bg}" :foreground "${colors.fg-dim}"))))
         `(vertical-border ((,class (:foreground "${colors.border}"))))
         `(window-divider ((,class (:foreground "${colors.border}"))))
         `(window-divider-first-pixel ((,class (:foreground "${colors.border}"))))
         `(window-divider-last-pixel ((,class (:foreground "${colors.border}"))))

         ;; Mode line
         `(mode-line ((,class (:background "${colors.bg-alt}" :foreground "${colors.fg}" :box (:line-width 2 :color "${colors.border}")))))
         `(mode-line-inactive ((,class (:background "${colors.bg}" :foreground "${colors.fg-dim}" :box (:line-width 2 :color "${colors.border}")))))
         `(mode-line-buffer-id ((,class (:foreground "${colors.blue}" :weight bold))))
         `(mode-line-emphasis ((,class (:foreground "${colors.green}" :weight bold))))

         ;; Line numbers
         `(line-number ((,class (:foreground "${colors.fg-dim}" :background "${colors.bg}"))))
         `(line-number-current-line ((,class (:foreground "${colors.fg-alt}" :background "${colors.bg-alt}"))))

         ;; Font lock (syntax highlighting)
         `(font-lock-comment-face ((,class (:foreground "${colors.fg-dim}" :slant italic))))
         `(font-lock-doc-face ((,class (:foreground "${colors.fg-dim}" :slant italic))))
         `(font-lock-string-face ((,class (:foreground "${colors.teal}"))))
         `(font-lock-keyword-face ((,class (:foreground "${colors.purple}" :weight bold))))
         `(font-lock-builtin-face ((,class (:foreground "${colors.cyan}"))))
         `(font-lock-function-name-face ((,class (:foreground "${colors.blue}"))))
         `(font-lock-variable-name-face ((,class (:foreground "${colors.fg}"))))
         `(font-lock-type-face ((,class (:foreground "${colors.yellow}"))))
         `(font-lock-constant-face ((,class (:foreground "${colors.orange}"))))
         `(font-lock-warning-face ((,class (:foreground "${colors.orange}" :weight bold))))
         `(font-lock-preprocessor-face ((,class (:foreground "${colors.purple}"))))

         ;; Search
         `(isearch ((,class (:foreground "${colors.bg}" :background "${colors.orange}" :weight bold))))
         `(lazy-highlight ((,class (:foreground "${colors.bg}" :background "${colors.yellow}"))))
         `(match ((,class (:foreground "${colors.bg}" :background "${colors.blue}"))))

         ;; Links
         `(link ((,class (:foreground "${colors.blue}" :underline t))))
         `(link-visited ((,class (:foreground "${colors.purple}" :underline t))))

         ;; Minibuffer
         `(minibuffer-prompt ((,class (:foreground "${colors.blue}" :weight bold))))

         ;; Messages
         `(error ((,class (:foreground "${colors.red}" :weight bold))))
         `(warning ((,class (:foreground "${colors.orange}" :weight bold))))
         `(success ((,class (:foreground "${colors.green}" :weight bold))))

         ;; Company (completion)
         `(company-tooltip ((,class (:background "${colors.bg-alt}" :foreground "${colors.fg}"))))
         `(company-tooltip-selection ((,class (:background "${colors.bg-highlight}" :foreground "${colors.fg}"))))
         `(company-tooltip-common ((,class (:foreground "${colors.blue}" :weight bold))))
         `(company-tooltip-annotation ((,class (:foreground "${colors.fg-dim}"))))
         `(company-scrollbar-bg ((,class (:background "${colors.bg-alt}"))))
         `(company-scrollbar-fg ((,class (:background "${colors.border}"))))

         ;; Org mode
         `(org-level-1 ((,class (:foreground "${colors.blue}" :weight bold :height 1.3))))
         `(org-level-2 ((,class (:foreground "${colors.cyan}" :weight bold :height 1.2))))
         `(org-level-3 ((,class (:foreground "${colors.green}" :weight bold :height 1.1))))
         `(org-level-4 ((,class (:foreground "${colors.yellow}" :weight bold))))
         `(org-level-5 ((,class (:foreground "${colors.orange}" :weight bold))))
         `(org-level-6 ((,class (:foreground "${colors.purple}" :weight bold))))
         `(org-level-7 ((,class (:foreground "${colors.red}" :weight bold))))
         `(org-level-8 ((,class (:foreground "${colors.fg-alt}" :weight bold))))
         `(org-link ((,class (:foreground "${colors.blue}" :underline t))))
         `(org-document-title ((,class (:foreground "${colors.blue}" :weight bold :height 1.4))))
         `(org-document-info ((,class (:foreground "${colors.cyan}"))))
         `(org-document-info-keyword ((,class (:foreground "${colors.fg-dim}"))))
         `(org-code ((,class (:foreground "${colors.teal}" :background "${colors.bg-alt}"))))
         `(org-verbatim ((,class (:foreground "${colors.orange}"))))
         `(org-block ((,class (:background "${colors.bg-alt}"))))
         `(org-block-begin-line ((,class (:foreground "${colors.fg-dim}" :background "${colors.bg-alt}"))))
         `(org-block-end-line ((,class (:foreground "${colors.fg-dim}" :background "${colors.bg-alt}"))))
         `(org-meta-line ((,class (:foreground "${colors.fg-dim}"))))
         `(org-date ((,class (:foreground "${colors.cyan}" :underline t))))
         `(org-todo ((,class (:foreground "${colors.red}" :weight bold))))
         `(org-done ((,class (:foreground "${colors.green}" :weight bold))))
         `(org-special-keyword ((,class (:foreground "${colors.purple}"))))
         `(org-table ((,class (:foreground "${colors.fg-alt}"))))

         ;; Dired
         `(dired-directory ((,class (:foreground "${colors.blue}" :weight bold))))
         `(dired-symlink ((,class (:foreground "${colors.cyan}"))))
         `(dired-marked ((,class (:foreground "${colors.green}" :weight bold))))
         `(dired-flagged ((,class (:foreground "${colors.red}" :weight bold))))

         ;; Diff
         `(diff-added ((,class (:foreground "${colors.green}" :background "${colors.bg-alt}"))))
         `(diff-removed ((,class (:foreground "${colors.red}" :background "${colors.bg-alt}"))))
         `(diff-changed ((,class (:foreground "${colors.blue}" :background "${colors.bg-alt}"))))
         `(diff-header ((,class (:foreground "${colors.fg-alt}" :background "${colors.bg-alt}"))))
         `(diff-file-header ((,class (:foreground "${colors.blue}" :weight bold))))
         `(diff-refine-added ((,class (:foreground "${colors.green}" :background "${colors.bg-highlight}"))))
         `(diff-refine-removed ((,class (:foreground "${colors.red}" :background "${colors.bg-highlight}"))))

         ;; Magit
         `(magit-header-line ((,class (:foreground "${colors.blue}" :weight bold))))
         `(magit-section-heading ((,class (:foreground "${colors.blue}" :weight bold))))
         `(magit-section-highlight ((,class (:background "${colors.bg-alt}"))))
         `(magit-diff-added ((,class (:foreground "${colors.green}" :background "${colors.bg-alt}"))))
         `(magit-diff-removed ((,class (:foreground "${colors.red}" :background "${colors.bg-alt}"))))
         `(magit-diff-added-highlight ((,class (:foreground "${colors.green}" :background "${colors.bg-highlight}"))))
         `(magit-diff-removed-highlight ((,class (:foreground "${colors.red}" :background "${colors.bg-highlight}"))))
         `(magit-diff-context ((,class (:foreground "${colors.fg-alt}" :background "${colors.bg}"))))
         `(magit-diff-context-highlight ((,class (:foreground "${colors.fg-alt}" :background "${colors.bg-alt}"))))
         `(magit-branch-local ((,class (:foreground "${colors.blue}"))))
         `(magit-branch-remote ((,class (:foreground "${colors.green}"))))
         `(magit-tag ((,class (:foreground "${colors.yellow}"))))
         `(magit-hash ((,class (:foreground "${colors.fg-dim}"))))

         ;; Show paren
         `(show-paren-match ((,class (:background "${colors.bg-highlight}" :foreground "${colors.blue}" :weight bold))))
         `(show-paren-mismatch ((,class (:background "${colors.red}" :foreground "${colors.bg}" :weight bold))))))

      (provide-theme 'signal)

      ;; Load the theme
      (load-theme 'signal t)
    '';
  };
}
