{
  config,
  lib,
  signalColors,
  signalLib,
  ...
}:
# CONFIGURATION METHOD: raw-config (Tier 4)
# HOME-MANAGER MODULE: programs.vim.extraConfig
# UPSTREAM SCHEMA: https://vimhelp.org/syntax.txt.html
# SCHEMA VERSION: 9.0
# LAST VALIDATED: 2026-01-17
# NOTES: Vim requires Vimscript for colorscheme definition. Home-Manager provides
#        extraConfig for custom Vimscript. We generate a complete colorscheme using
#        highlight commands. No structured options exist for custom themes.
let
  inherit (lib) mkIf;
  cfg = config.theming.signal;

  colors = {
    # Base colors
    bg = signalColors.tonal."surface-Lc05".hex;
    bg_alt = signalColors.tonal."surface-Lc10".hex;
    fg = signalColors.tonal."text-Lc75".hex;
    fg_alt = signalColors.tonal."text-Lc60".hex;
    fg_dim = signalColors.tonal."text-Lc45".hex;

    # Accent colors
    blue = signalColors.accent.focus.Lc75.hex;
    cyan = signalColors.accent.info.Lc75.hex;
    green = signalColors.accent.success.Lc75.hex;
    red = signalColors.accent.danger.Lc75.hex;
    orange = signalColors.accent.warning.Lc75.hex;
    purple = signalColors.accent.special.Lc75.hex;

    # Categorical colors
    yellow = signalColors.categorical.GA04.hex;
    teal = signalColors.categorical.GA02.hex;

    # UI colors
    border = signalColors.tonal."divider-Lc15".hex;
    selection = signalColors.tonal."divider-Lc15".hex;
  };

  # Check if vim should be themed
  shouldTheme = signalLib.shouldThemeApp "vim" [
    "editors"
    "vim"
  ] cfg config;
in
{
  config = mkIf (cfg.enable && shouldTheme) {
    programs.vim.extraConfig = ''
      " Signal Vim Colorscheme
      " Generated by signal-nix

      set background=${if cfg.mode == "light" then "light" else "dark"}

      highlight clear
      if exists("syntax_on")
        syntax reset
      endif

      let g:colors_name = "signal"

      " Editor colors
      highlight Normal guifg=${colors.fg} guibg=${colors.bg}
      highlight LineNr guifg=${colors.fg_dim} guibg=${colors.bg}
      highlight CursorLineNr guifg=${colors.fg} guibg=${colors.bg_alt}
      highlight CursorLine guibg=${colors.bg_alt}
      highlight CursorColumn guibg=${colors.bg_alt}
      highlight ColorColumn guibg=${colors.bg_alt}
      highlight Visual guibg=${colors.selection}
      highlight VisualNOS guibg=${colors.selection}
      highlight Search guifg=${colors.bg} guibg=${colors.yellow}
      highlight IncSearch guifg=${colors.bg} guibg=${colors.orange}
      highlight MatchParen guifg=${colors.blue} guibg=${colors.selection} gui=bold

      " UI Elements
      highlight StatusLine guifg=${colors.fg} guibg=${colors.bg_alt}
      highlight StatusLineNC guifg=${colors.fg_dim} guibg=${colors.bg_alt}
      highlight VertSplit guifg=${colors.border} guibg=${colors.bg}
      highlight TabLine guifg=${colors.fg_dim} guibg=${colors.bg_alt}
      highlight TabLineFill guibg=${colors.bg_alt}
      highlight TabLineSel guifg=${colors.fg} guibg=${colors.bg}
      highlight Pmenu guifg=${colors.fg} guibg=${colors.bg_alt}
      highlight PmenuSel guifg=${colors.bg} guibg=${colors.blue}
      highlight PmenuSbar guibg=${colors.bg_alt}
      highlight PmenuThumb guibg=${colors.fg_dim}
      highlight Folded guifg=${colors.fg_dim} guibg=${colors.bg_alt}
      highlight FoldColumn guifg=${colors.fg_dim} guibg=${colors.bg}

      " Messages
      highlight ErrorMsg guifg=${colors.red}
      highlight WarningMsg guifg=${colors.orange}
      highlight ModeMsg guifg=${colors.green}
      highlight MoreMsg guifg=${colors.cyan}
      highlight Question guifg=${colors.blue}

      " Syntax highlighting
      highlight Comment guifg=${colors.fg_dim} gui=italic
      highlight Constant guifg=${colors.orange}
      highlight String guifg=${colors.teal}
      highlight Character guifg=${colors.green}
      highlight Number guifg=${colors.orange}
      highlight Boolean guifg=${colors.orange}
      highlight Float guifg=${colors.orange}
      
      highlight Identifier guifg=${colors.fg}
      highlight Function guifg=${colors.blue}
      
      highlight Statement guifg=${colors.purple}
      highlight Conditional guifg=${colors.purple}
      highlight Repeat guifg=${colors.purple}
      highlight Label guifg=${colors.purple}
      highlight Operator guifg=${colors.cyan}
      highlight Keyword guifg=${colors.purple}
      highlight Exception guifg=${colors.red}
      
      highlight PreProc guifg=${colors.purple}
      highlight Include guifg=${colors.purple}
      highlight Define guifg=${colors.purple}
      highlight Macro guifg=${colors.purple}
      highlight PreCondit guifg=${colors.purple}
      
      highlight Type guifg=${colors.yellow}
      highlight StorageClass guifg=${colors.purple}
      highlight Structure guifg=${colors.yellow}
      highlight Typedef guifg=${colors.yellow}
      
      highlight Special guifg=${colors.cyan}
      highlight SpecialChar guifg=${colors.cyan}
      highlight Tag guifg=${colors.blue}
      highlight Delimiter guifg=${colors.fg_alt}
      highlight SpecialComment guifg=${colors.cyan} gui=italic
      highlight Debug guifg=${colors.red}
      
      highlight Underlined guifg=${colors.blue} gui=underline
      highlight Ignore guifg=${colors.fg_dim}
      highlight Error guifg=${colors.red} guibg=${colors.bg}
      highlight Todo guifg=${colors.purple} guibg=${colors.bg} gui=bold

      " Diff colors
      highlight DiffAdd guifg=${colors.green} guibg=${colors.bg_alt}
      highlight DiffChange guifg=${colors.blue} guibg=${colors.bg_alt}
      highlight DiffDelete guifg=${colors.red} guibg=${colors.bg_alt}
      highlight DiffText guifg=${colors.blue} guibg=${colors.selection}

      " Spell checking
      highlight SpellBad guisp=${colors.red} gui=undercurl
      highlight SpellCap guisp=${colors.yellow} gui=undercurl
      highlight SpellLocal guisp=${colors.cyan} gui=undercurl
      highlight SpellRare guisp=${colors.purple} gui=undercurl

      " Terminal colors (for :terminal)
      let g:terminal_ansi_colors = [
      \ '${signalColors.tonal."base-L015".hex}',
      \ '${signalColors.accent.danger.Lc75.hex}',
      \ '${signalColors.accent.success.Lc75.hex}',
      \ '${signalColors.accent.warning.Lc75.hex}',
      \ '${signalColors.accent.focus.Lc75.hex}',
      \ '${signalColors.accent.special.Lc75.hex}',
      \ '${signalColors.accent.info.Lc75.hex}',
      \ '${signalColors.tonal."text-Lc60".hex}',
      \ '${signalColors.tonal."text-Lc45".hex}',
      \ '${signalColors.accent.danger.Lc75.hex}',
      \ '${signalColors.accent.success.Lc75.hex}',
      \ '${signalColors.accent.warning.Lc75.hex}',
      \ '${signalColors.accent.focus.Lc75.hex}',
      \ '${signalColors.accent.special.Lc75.hex}',
      \ '${signalColors.accent.info.Lc75.hex}',
      \ '${signalColors.tonal."text-Lc75".hex}',
      \ ]
    '';
  };
}
