name: Feature Request
description: Suggest a new feature or enhancement for Signal
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What kind of feature are you requesting?
      options:
        - New Application Integration
        - Enhancement to Existing Integration
        - New Color Token
        - Brand Governance Feature
        - Library Function
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've thought about...

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would be used
      placeholder: |
        theming.signal.newFeature = {
          enable = true;
          option = "value";
        };
      render: nix

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this require breaking changes to existing configurations?
      options:
        - "No"
        - "Yes"
        - "Unsure"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my workflow
        - High - Would significantly improve my experience
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions to avoid duplicates
          required: true
        - label: This feature aligns with Signal's philosophy (scientific, accessible, perceptually uniform)
          required: false
        - label: I am willing to help implement this feature
          required: false
