{
  config,
  lib,

  signalLib,
  ...
}:
# CONFIGURATION METHOD: raw-config (Tier 4)
# HOME-MANAGER MODULE: programs.bash.initExtra
# UPSTREAM SCHEMA: https://www.gnu.org/software/bash/manual/html_node/Controlling-the-Prompt.html
# SCHEMA VERSION: 5.2
# LAST VALIDATED: 2026-01-17
# NOTES: Bash uses ANSI escape codes for colors via PS1 and LS_COLORS.
#        Home-Manager provides initExtra for custom bash commands.
let
  inherit (lib) mkIf;
  cfg = config.theming.signal;
  themeMode = signalLib.resolveThemeMode cfg.mode;
  signalColors = signalLib.getColors themeMode;

  colors = {
    text-primary = signalColors.tonal."text-primary";
    text-secondary = signalColors.tonal."text-secondary";
    text-dim = signalColors.tonal."text-tertiary";
  };

  inherit (signalColors) accent;

  # Helper to convert hex color to ANSI RGB string (38;2;R;G;B)
  # Uses signalLib's RGB conversion which leverages nix-colorizer
  toAnsiRgb =
    color:
    let
      rgb = signalLib.hexToRgbSpaceSeparated color;
      parts = lib.splitString " " rgb;
    in
    "38;2;${lib.concatStringsSep ";" parts}";

  # Convert hex to ANSI RGB code for PS1 prompts (with bash escape sequences)
  toPs1Rgb = color: "\\[\\e[${toAnsiRgb color}m\\]";

  # Check if bash should be themed
  shouldTheme = signalLib.shouldThemeApp "bash" [
    "shells"
    "bash"
  ] cfg config;
in
{
  config = mkIf (cfg.enable && shouldTheme) {
    programs.bash.initExtra = ''
            # Signal bash colors - generated by signal-nix

            # LS_COLORS for file listing (dircolors format)
            export LS_COLORS="rs=0:\
      di=${toAnsiRgb accent.secondary.Lc75}:\
      ln=${toAnsiRgb accent.secondary.Lc75}:\
      mh=00:\
      pi=${toAnsiRgb accent.warning.Lc75}:\
      so=${toAnsiRgb accent.tertiary.Lc75}:\
      do=${toAnsiRgb accent.tertiary.Lc75}:\
      bd=${toAnsiRgb accent.warning.Lc75}:\
      cd=${toAnsiRgb accent.warning.Lc75}:\
      or=${toAnsiRgb accent.danger.Lc75}:\
      mi=${toAnsiRgb accent.danger.Lc75}:\
      su=${toAnsiRgb accent.danger.Lc75}:\
      sg=${toAnsiRgb accent.warning.Lc75}:\
      ca=${toAnsiRgb accent.secondary.Lc75}:\
      tw=${toAnsiRgb accent.primary.Lc75}:\
      ow=${toAnsiRgb accent.primary.Lc75}:\
      st=${toAnsiRgb accent.secondary.Lc75}:\
      ex=${toAnsiRgb accent.primary.Lc75}:\
      *.tar=${toAnsiRgb accent.tertiary.Lc75}:\
      *.tgz=${toAnsiRgb accent.tertiary.Lc75}:\
      *.zip=${toAnsiRgb accent.tertiary.Lc75}:\
      *.gz=${toAnsiRgb accent.tertiary.Lc75}:\
      *.bz2=${toAnsiRgb accent.tertiary.Lc75}:\
      *.xz=${toAnsiRgb accent.tertiary.Lc75}:\
      *.jpg=${toAnsiRgb signalColors.categorical."data-viz-06"}:\
      *.jpeg=${toAnsiRgb signalColors.categorical."data-viz-06"}:\
      *.png=${toAnsiRgb signalColors.categorical."data-viz-06"}:\
      *.gif=${toAnsiRgb signalColors.categorical."data-viz-06"}:\
      *.mp3=${toAnsiRgb signalColors.categorical."data-viz-08"}:\
      *.mp4=${toAnsiRgb signalColors.categorical."data-viz-08"}:\
      *.avi=${toAnsiRgb signalColors.categorical."data-viz-08"}:\
      *.mkv=${toAnsiRgb signalColors.categorical."data-viz-08"}"

            # Grep colors
            export GREP_COLORS="mt=${toAnsiRgb accent.secondary.Lc75}:\
      fn=${toAnsiRgb accent.secondary.Lc75}:\
      ln=${toAnsiRgb accent.primary.Lc75}:\
      se=${toAnsiRgb colors.text-dim}"

            # Less colors (for man pages)
            export LESS_TERMCAP_mb=\\e[${toAnsiRgb accent.danger.Lc75}m     # begin blinking
            export LESS_TERMCAP_md=\\e[${toAnsiRgb accent.secondary.Lc75}m      # begin bold
            export LESS_TERMCAP_me=\\e[0m                         # end mode
            export LESS_TERMCAP_se=\\e[0m                         # end standout-mode
            export LESS_TERMCAP_so=\\e[${toAnsiRgb accent.warning.Lc75}m    # begin standout-mode
            export LESS_TERMCAP_ue=\\e[0m                         # end underline
            export LESS_TERMCAP_us=\\e[${toAnsiRgb accent.primary.Lc75}m    # begin underline
    '';

    # Also set a colored PS1 if not already customized
    programs.bash.bashrcExtra = lib.mkIf (!config.programs.bash ? promptInit) ''
      # Signal-themed PS1 prompt
      if [ -z "$PROMPT_COMMAND" ]; then
        PS1="${toPs1Rgb accent.primary.Lc75}\\u${toPs1Rgb colors.text-secondary}@${toPs1Rgb accent.secondary.Lc75}\\h ${toPs1Rgb accent.secondary.Lc75}\\w ${toPs1Rgb colors.text-primary}\\$ \\[\\e[0m\\]"
      fi
    '';
  };
}
