{
  config,
  lib,
  signalColors,
  signalLib,
  ...
}:
# CONFIGURATION METHOD: raw-config (Tier 4)
# HOME-MANAGER MODULE: programs.bash.initExtra
# UPSTREAM SCHEMA: https://www.gnu.org/software/bash/manual/html_node/Controlling-the-Prompt.html
# SCHEMA VERSION: 5.2
# LAST VALIDATED: 2026-01-17
# NOTES: Bash uses ANSI escape codes for colors via PS1 and LS_COLORS.
#        Home-Manager provides initExtra for custom bash commands.
let
  inherit (lib) mkIf;
  cfg = config.theming.signal;

  colors = {
    text-primary = signalColors.tonal."text-Lc75";
    text-secondary = signalColors.tonal."text-Lc60";
    text-dim = signalColors.tonal."text-Lc45";
  };

  inherit (signalColors) accent;

  # Convert hex to ANSI RGB code
  toAnsiRgb = color:
    let
      hex = lib.removePrefix "#" color.hex;
      r = lib.toInt "0x${builtins.substring 0 2 hex}";
      g = lib.toInt "0x${builtins.substring 2 2 hex}";
      b = lib.toInt "0x${builtins.substring 4 2 hex}";
    in
    "\\[\\e[38;2;${toString r};${toString g};${toString b}m\\]";

  # Check if bash should be themed
  shouldTheme = signalLib.shouldThemeApp "bash" [
    "shells"
    "bash"
  ] cfg config;
in
{
  config = mkIf (cfg.enable && shouldTheme) {
    programs.bash.initExtra = ''
      # Signal bash colors - generated by signal-nix

      # LS_COLORS for file listing (dircolors format)
      export LS_COLORS="rs=0:\
di=${toAnsiRgb accent.focus.Lc75}:\
ln=${toAnsiRgb accent.info.Lc75}:\
mh=00:\
pi=${toAnsiRgb accent.warning.Lc75}:\
so=${toAnsiRgb accent.special.Lc75}:\
do=${toAnsiRgb accent.special.Lc75}:\
bd=${toAnsiRgb accent.warning.Lc75}:\
cd=${toAnsiRgb accent.warning.Lc75}:\
or=${toAnsiRgb accent.danger.Lc75}:\
mi=${toAnsiRgb accent.danger.Lc75}:\
su=${toAnsiRgb accent.danger.Lc75}:\
sg=${toAnsiRgb accent.warning.Lc75}:\
ca=${toAnsiRgb accent.info.Lc75}:\
tw=${toAnsiRgb accent.success.Lc75}:\
ow=${toAnsiRgb accent.success.Lc75}:\
st=${toAnsiRgb accent.focus.Lc75}:\
ex=${toAnsiRgb accent.success.Lc75}:\
*.tar=${toAnsiRgb accent.special.Lc75}:\
*.tgz=${toAnsiRgb accent.special.Lc75}:\
*.zip=${toAnsiRgb accent.special.Lc75}:\
*.gz=${toAnsiRgb accent.special.Lc75}:\
*.bz2=${toAnsiRgb accent.special.Lc75}:\
*.xz=${toAnsiRgb accent.special.Lc75}:\
*.jpg=${toAnsiRgb signalColors.categorical.GA06}:\
*.jpeg=${toAnsiRgb signalColors.categorical.GA06}:\
*.png=${toAnsiRgb signalColors.categorical.GA06}:\
*.gif=${toAnsiRgb signalColors.categorical.GA06}:\
*.mp3=${toAnsiRgb signalColors.categorical.GA08}:\
*.mp4=${toAnsiRgb signalColors.categorical.GA08}:\
*.avi=${toAnsiRgb signalColors.categorical.GA08}:\
*.mkv=${toAnsiRgb signalColors.categorical.GA08}"

      # Grep colors
      export GREP_COLORS="mt=${toAnsiRgb accent.focus.Lc75}:\
fn=${toAnsiRgb accent.info.Lc75}:\
ln=${toAnsiRgb accent.success.Lc75}:\
se=${toAnsiRgb colors.text-dim}"

      # Less colors (for man pages)
      export LESS_TERMCAP_mb=${toAnsiRgb accent.danger.Lc75}     # begin blinking
      export LESS_TERMCAP_md=${toAnsiRgb accent.focus.Lc75}      # begin bold
      export LESS_TERMCAP_me=\\[\\e[0m\\]                         # end mode
      export LESS_TERMCAP_se=\\[\\e[0m\\]                         # end standout-mode
      export LESS_TERMCAP_so=${toAnsiRgb accent.warning.Lc75}    # begin standout-mode
      export LESS_TERMCAP_ue=\\[\\e[0m\\]                         # end underline
      export LESS_TERMCAP_us=${toAnsiRgb accent.success.Lc75}    # begin underline
    '';

    # Also set a colored PS1 if not already customized
    programs.bash.bashrcExtra = lib.mkIf (!config.programs.bash ? promptInit) ''
      # Signal-themed PS1 prompt
      if [ -z "$PROMPT_COMMAND" ]; then
        PS1="${toAnsiRgb accent.success.Lc75}\\u${toAnsiRgb colors.text-secondary}@${toAnsiRgb accent.info.Lc75}\\h ${toAnsiRgb accent.focus.Lc75}\\w ${toAnsiRgb colors.text-primary}\\$ \\[\\e[0m\\]"
      fi
    '';
  };
}
