{
  config,
  lib,
  signalColors,
  signalLib,
  ...
}:
# CONFIGURATION METHOD: raw-config (Tier 4)
# HOME-MANAGER MODULE: programs.bash.initExtra
# UPSTREAM SCHEMA: https://www.gnu.org/software/bash/manual/html_node/Controlling-the-Prompt.html
# SCHEMA VERSION: 5.2
# LAST VALIDATED: 2026-01-17
# NOTES: Bash uses ANSI escape codes for colors via PS1 and LS_COLORS.
#        Home-Manager provides initExtra for custom bash commands.
let
  inherit (lib) mkIf;
  cfg = config.theming.signal;

  colors = {
    text-primary = signalColors.tonal."text-primary";
    text-secondary = signalColors.tonal."text-secondary";
    text-dim = signalColors.tonal."text-tertiary";
  };

  inherit (signalColors) accent;

  # Convert a hex digit to decimal (0-15)
  hexDigitToInt = c:
    let
      lowerC = lib.toLower c;
    in
    if lowerC == "0" then 0
    else if lowerC == "1" then 1
    else if lowerC == "2" then 2
    else if lowerC == "3" then 3
    else if lowerC == "4" then 4
    else if lowerC == "5" then 5
    else if lowerC == "6" then 6
    else if lowerC == "7" then 7
    else if lowerC == "8" then 8
    else if lowerC == "9" then 9
    else if lowerC == "a" then 10
    else if lowerC == "b" then 11
    else if lowerC == "c" then 12
    else if lowerC == "d" then 13
    else if lowerC == "e" then 14
    else if lowerC == "f" then 15
    else throw "Invalid hex digit: ${c}";

  # Convert a 2-character hex string to decimal (0-255)
  hexPairToInt = pair:
    let
      first = hexDigitToInt (builtins.substring 0 1 pair);
      second = hexDigitToInt (builtins.substring 1 1 pair);
    in
    first * 16 + second;

  # Convert hex to ANSI RGB code for environment variables (no prompt escaping)
  toAnsiRgb =
    color:
    let
      hex = lib.removePrefix "#" color.hex;
      r = hexPairToInt (builtins.substring 0 2 hex);
      g = hexPairToInt (builtins.substring 2 2 hex);
      b = hexPairToInt (builtins.substring 4 2 hex);
    in
    "38;2;${toString r};${toString g};${toString b}";

  # Convert hex to ANSI RGB code for PS1 prompts (with bash escape sequences)
  toPs1Rgb =
    color:
    let
      hex = lib.removePrefix "#" color.hex;
      r = hexPairToInt (builtins.substring 0 2 hex);
      g = hexPairToInt (builtins.substring 2 2 hex);
      b = hexPairToInt (builtins.substring 4 2 hex);
    in
    "\\[\\e[38;2;${toString r};${toString g};${toString b}m\\]";

  # Check if bash should be themed
  shouldTheme = signalLib.shouldThemeApp "bash" [
    "shells"
    "bash"
  ] cfg config;
in
{
  config = mkIf (cfg.enable && shouldTheme) {
    programs.bash.initExtra = ''
            # Signal bash colors - generated by signal-nix

            # LS_COLORS for file listing (dircolors format)
            export LS_COLORS="rs=0:\
      di=${toAnsiRgb accent.secondary.Lc75}:\
      ln=${toAnsiRgb accent.secondary.Lc75}:\
      mh=00:\
      pi=${toAnsiRgb accent.warning.Lc75}:\
      so=${toAnsiRgb accent.tertiary.Lc75}:\
      do=${toAnsiRgb accent.tertiary.Lc75}:\
      bd=${toAnsiRgb accent.warning.Lc75}:\
      cd=${toAnsiRgb accent.warning.Lc75}:\
      or=${toAnsiRgb accent.danger.Lc75}:\
      mi=${toAnsiRgb accent.danger.Lc75}:\
      su=${toAnsiRgb accent.danger.Lc75}:\
      sg=${toAnsiRgb accent.warning.Lc75}:\
      ca=${toAnsiRgb accent.secondary.Lc75}:\
      tw=${toAnsiRgb accent.primary.Lc75}:\
      ow=${toAnsiRgb accent.primary.Lc75}:\
      st=${toAnsiRgb accent.secondary.Lc75}:\
      ex=${toAnsiRgb accent.primary.Lc75}:\
      *.tar=${toAnsiRgb accent.tertiary.Lc75}:\
      *.tgz=${toAnsiRgb accent.tertiary.Lc75}:\
      *.zip=${toAnsiRgb accent.tertiary.Lc75}:\
      *.gz=${toAnsiRgb accent.tertiary.Lc75}:\
      *.bz2=${toAnsiRgb accent.tertiary.Lc75}:\
      *.xz=${toAnsiRgb accent.tertiary.Lc75}:\
      *.jpg=${toAnsiRgb signalColors.categorical."data-viz-06"}:\
      *.jpeg=${toAnsiRgb signalColors.categorical."data-viz-06"}:\
      *.png=${toAnsiRgb signalColors.categorical."data-viz-06"}:\
      *.gif=${toAnsiRgb signalColors.categorical."data-viz-06"}:\
      *.mp3=${toAnsiRgb signalColors.categorical."data-viz-08"}:\
      *.mp4=${toAnsiRgb signalColors.categorical."data-viz-08"}:\
      *.avi=${toAnsiRgb signalColors.categorical."data-viz-08"}:\
      *.mkv=${toAnsiRgb signalColors.categorical."data-viz-08"}"

            # Grep colors
            export GREP_COLORS="mt=${toAnsiRgb accent.secondary.Lc75}:\
      fn=${toAnsiRgb accent.secondary.Lc75}:\
      ln=${toAnsiRgb accent.primary.Lc75}:\
      se=${toAnsiRgb colors.text-dim}"

            # Less colors (for man pages)
            export LESS_TERMCAP_mb=\\e[${toAnsiRgb accent.danger.Lc75}m     # begin blinking
            export LESS_TERMCAP_md=\\e[${toAnsiRgb accent.secondary.Lc75}m      # begin bold
            export LESS_TERMCAP_me=\\e[0m                         # end mode
            export LESS_TERMCAP_se=\\e[0m                         # end standout-mode
            export LESS_TERMCAP_so=\\e[${toAnsiRgb accent.warning.Lc75}m    # begin standout-mode
            export LESS_TERMCAP_ue=\\e[0m                         # end underline
            export LESS_TERMCAP_us=\\e[${toAnsiRgb accent.primary.Lc75}m    # begin underline
    '';

    # Also set a colored PS1 if not already customized
    programs.bash.bashrcExtra = lib.mkIf (!config.programs.bash ? promptInit) ''
      # Signal-themed PS1 prompt
      if [ -z "$PROMPT_COMMAND" ]; then
        PS1="${toPs1Rgb accent.primary.Lc75}\\u${toPs1Rgb colors.text-secondary}@${toPs1Rgb accent.secondary.Lc75}\\h ${toPs1Rgb accent.secondary.Lc75}\\w ${toPs1Rgb colors.text-primary}\\$ \\[\\e[0m\\]"
      fi
    '';
  };
}
