{
  config,
  lib,
  signalColors,
  signalLib,
  ...
}:
# CONFIGURATION METHOD: raw-config (Tier 4)
# HOME-MANAGER MODULE: programs.fish.shellInit
# UPSTREAM SCHEMA: https://fishshell.com/docs/current/interactive.html#syntax-highlighting
# SCHEMA VERSION: 3.7.0
# LAST VALIDATED: 2026-01-17
# NOTES: Fish uses set commands to configure colors. Home-Manager provides shellInit
#        for custom Fish commands. We set all fish_color_* variables.
let
  inherit (lib) mkIf;
  cfg = config.theming.signal;

  colors = {
    text-primary = signalColors.tonal."text-primary";
    text-secondary = signalColors.tonal."text-secondary";
    text-dim = signalColors.tonal."text-tertiary";
    divider = signalColors.tonal."divider-primary";
  };

  inherit (signalColors) accent;

  # Fish color format: hex without #
  toFishColor = color: lib.removePrefix "#" color.hex;

  # Check if fish should be themed
  shouldTheme = signalLib.shouldThemeApp "fish" [
    "shells"
    "fish"
  ] cfg config;
in
{
  config = mkIf (cfg.enable && shouldTheme) {
    programs.fish.shellInit = ''
      # Signal fish colors - generated by signal-nix

      # Syntax highlighting colors
      set -g fish_color_normal ${toFishColor colors.text-primary}
      set -g fish_color_command ${toFishColor accent.secondary.Lc75}
      set -g fish_color_keyword ${toFishColor accent.tertiary.Lc75}
      set -g fish_color_quote ${toFishColor signalColors.categorical."data-viz-02"}
      set -g fish_color_redirection ${toFishColor accent.secondary.Lc75}
      set -g fish_color_end ${toFishColor colors.text-secondary}
      set -g fish_color_error ${toFishColor accent.danger.Lc75}
      set -g fish_color_param ${toFishColor colors.text-primary}
      set -g fish_color_option ${toFishColor colors.text-secondary}
      set -g fish_color_comment ${toFishColor colors.text-dim}
      set -g fish_color_selection --background=${toFishColor colors.divider}
      set -g fish_color_operator ${toFishColor accent.secondary.Lc75}
      set -g fish_color_escape ${toFishColor signalColors.categorical."data-viz-08"}
      set -g fish_color_autosuggestion ${toFishColor colors.text-dim}

      # Completion pager colors
      set -g fish_pager_color_progress ${toFishColor accent.secondary.Lc75}
      set -g fish_pager_color_background
      set -g fish_pager_color_prefix ${toFishColor accent.secondary.Lc75} --bold
      set -g fish_pager_color_completion ${toFishColor colors.text-primary}
      set -g fish_pager_color_description ${toFishColor colors.text-dim}
      set -g fish_pager_color_selected_background --background=${toFishColor colors.divider}
      set -g fish_pager_color_selected_prefix ${toFishColor accent.secondary.Lc75} --bold
      set -g fish_pager_color_selected_completion ${toFishColor colors.text-primary}
      set -g fish_pager_color_selected_description ${toFishColor colors.text-secondary}
      set -g fish_pager_color_secondary_background
      set -g fish_pager_color_secondary_prefix ${toFishColor accent.secondary.Lc75}
      set -g fish_pager_color_secondary_completion ${toFishColor colors.text-secondary}
      set -g fish_pager_color_secondary_description ${toFishColor colors.text-dim}

      # Search match color
      set -g fish_color_search_match --background=${toFishColor colors.divider}

      # Valid/invalid path colors
      set -g fish_color_valid_path --underline
      set -g fish_color_invalid_path ${toFishColor accent.danger.Lc75}

      # History search colors
      set -g fish_color_history_current ${toFishColor accent.secondary.Lc75} --bold

      # User/host colors (prompt)
      set -g fish_color_user ${toFishColor accent.primary.Lc75}
      set -g fish_color_host ${toFishColor accent.secondary.Lc75}
      set -g fish_color_host_remote ${toFishColor accent.warning.Lc75}

      # Cancel command color
      set -g fish_color_cancel ${toFishColor accent.danger.Lc75}
    '';
  };
}
